### ISSUE TITLE
Can buildout-versions made to work for zc.buildout  v1.4.*?

### ISSUE THREAD

**Issue by woutervh** [simplistix/buildout-versions#1]
I have not delved deep in to buildout-extensions, but  why can buildout.dumppickedversions be used with zc.buildout v1.4.*
while buildout-versions requires  1.5.0?

is it doable  to add compatibility for zc.buildout  v1.4.*?

**Comment by woutervh** [comment]
if you remove the dependency in setup.py.
and you add in your buildout "newest= false"     (so buildout does not try to upgrade itself to 1.5.+)

then everything seems to works fine.

**Comment by cjw296** [comment]
Hi Wouter,

On 20/10/2011 18:58, Wouter Vanden Hove wrote:

> I have not delved deep in to buildout-extensions, but  why can buildout.dumppickedversions be used with zc.buildout v1.4.*
> while buildout-versions requires  1.5.0?

buildout-versions has a bit more functionality that 
buildout.dumppickedversions now ;-)

> is it doable  to add compatibility for zc.buildout  v1.4.*?

What's stopping you moving to buildout 1.5?

Chris

## 

Simplistix - Content Management, Batch Processing & Python Consulting
             - http://www.simplistix.co.uk

**Comment by woutervh** [comment]
1) Plone is officially still using zc.buildout 1.4.*
   see for example  http://dist.plone.org/release/4.1.2/versions.cfg  refers to 
   http://download.zope.org/Zope2/index/2.13.10/versions.cfg  which refers to 
   http://download.zope.org/zopetoolkit/index/1.0.4/ztk-versions.cfg
   --> zc.buildout = 1.4.4

2) unrelated to that, I'd like to have my buildout-directories as a virtualenv
   but  virtualenv conflicts with zc.buildout >=1.5 
   see  http://mail.python.org/pipermail/distutils-sig/2010-April/016062.html
- https://github.com/pypa/virtualenv/issues/177  (opened today by me)
- https://github.com/pypa/virtualenv/issues/97

I started a new python-project with buildout 1.5,  but this virtualenv-issue forces me back to 1.4
which also currently forces me back to buildout.dumppickedversions.

**Comment by cjw296** [comment]
On 21/10/2011 19:29, Wouter Vanden Hove wrote:

> 1) Plone is officially still using zc.buildout 1.4.*
>     see for example  http://dist.plone.org/release/4.1.2/versions.cfg  refers to
>     http://download.zope.org/Zope2/index/2.13.10/versions.cfg  which refers to
>     http://download.zope.org/zopetoolkit/index/1.0.4/ztk-versions.cfg
>     -->  zc.buildout = 1.4.4

Yeah, but you'll be fine to specify a newer version of buildout, eg:

[buildout]
extends = http://dist.plone.org/release/4.1.2/versions.cfg
version = versions

[versions]
zc.buildout = 1.5.whatever

> 2) unrelated to that, I'd like to have my buildout-directories as a virtualenv
>     but  virtualenv conflicts with zc.buildout>=1.5
>     see  http://mail.python.org/pipermail/distutils-sig/2010-April/016062.html

Well, this is kind of irrelevant, buildout 1.5 makes wrapping the 
buildout in a virtualenv unnecessary...

cheers,

Chris

## 

Simplistix - Content Management, Batch Processing & Python Consulting
             - http://www.simplistix.co.uk
