### ISSUE TITLE
Speedup for _log_requirement()

### ISSUE THREAD

**Issue by mgedmin** [simplistix/buildout-versions#3]
Ross Patterson has been working on [a branch to speed up zc.buildout](http://mail.python.org/pipermail/distutils-sig/2012-January/018241.html).  While working on that he noticed that a function ([_log_requirement]()) is performing a lot of computation that is then discarded when the logging level is anything higher than DEBUG.  This function is also present in `buildout.dumppickedversions` and (I finally get to the point ;)) [buildout-versions](https://github.com/Simplistix/buildout-versions/blob/332070a04c326491ceb983f8ecf346612a564773/src/buildout_versions/__init__.py#L20).

Ross [fixed this in zc.buildout](http://svn.zope.org/zc.buildout/trunk/src/zc/buildout/easy_install.py?rev=124059&r1=122980&r2=124059) and in [buildout.dumppickedversions](http://pypi.python.org/pypi/buildout.dumppickedversions/0.5#id1) and then [compared the run time](http://mail.python.org/pipermail/distutils-sig/2012-January/018268.html) of buildout.dumppickedversions with buildout-versions:

> I just timed a production buildout with zc.buildout 1.5.2 and compared
> buildout.dumppickedversions 0.5 against buildout-versions 1.7.
> 
>     buildout.dumppickedversions 0.5 = 0m33.449s
>     buildout-versions 1.7           = 1m11.667s

He asked me (in private mail) to ping you, since I brought buildout-versions up in the discussion, and he doesn't use it personally, so I'm pinging you. ;)

I'll try to create a github pull request soon.

**Comment by mgedmin** [comment]
Here's the pull request: https://github.com/Simplistix/buildout-versions/pull/4

I probably didn't need to create an issue.  Oh well, Github is still new to me.

**Comment by cjw296** [comment]
Heh, GitHub's new to me too, don't worry ;-)

Unfortunately, that computation _is_ used whenever buildout-versions has to report non-specified packages.
(you ran the tests once you made the patch, right? ;-) )

Anyway, I removed the sort here:

https://github.com/Simplistix/buildout-versions/tree/speedup

Can you let me know how that performs, speed wise, for you?

**Comment by mgedmin** [comment]
The tests fail for me with this (on master as well as on my b0rken branch, sorry about that, by the way!):

```
Failure in test /home/mg/src/buildout-versions/docs/use.txt
...
  File "/home/mg/src/buildout-versions/docs/use.txt:27", line 3, in <module>
...
 The following part definition lists the versions picked:
 [versions]
 buildout-versions = 1.7
-setuptools = 0.6.24
+distribute = 0.6.24
 zc.buildout = 1.5.2
```

and, to be fair, I forgot to run them before deciding to submit the "trivial" pull request.

**Comment by cjw296** [comment]
Yeah, I don't intend to be trying to work around people who've poluted their system with distribute ;-)

Of course, things will work, but I'm not going to try bashing the tests to pass just 'cos you used bootstrap.py -d or have distribute in your system python...

**Comment by mgedmin** [comment]
I pinged Ross Patterson about the reporting issue (is buildout.dumppickedversions buggy now?) and asked if he could try your new branch on the same buildout where he previously saw a 2x difference (quoted at the beginning of this conversation).  I haven't observed any buildout-versions related slowdowns on any of my buildouts yet, so I don't have a test case handy.

Boy do I feel silly playing the middleman here...

**Comment by cjw296** [comment]
I wouldn't know about buildout.dumppickedversions, I forked it as it didn't appear to be maintained ;-)

**Comment by mgedmin** [comment]
Quoting Ross again:

> The buildout.dumppickedversions tests cover the inclusion of all the
> picked versions and those tests still passed after my change.

and about the test case that I don't have:

> > Since I don't have a test case (I was unable to notice the slowdown you
> > reported above), I wonder if I could impose on you to give it a try and
> > report your findings on the same buildout you mentioned here:
> 
> Nope. I've put that all away and as I've said before I don't use
> buildout-versions.

Oh well.  I thought this would be a simple and obvious cherry-pick, but given that I haven't experienced any slowdowns attributable to buildout-versions myself...

**Comment by cjw296** [comment]
Yeah, me neither, so I'll leave things as-is until someone actually has an issue ;-)

When that happens, we can re-open and pick up the speedup branch, which I will leave right where it is.
